# Generated by Django 5.0.6 on 2024-06-20 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
            ],
        ),
        migrations.CreateModel(
            name='HttpRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('protocol', models.CharField(choices=[('http', 'http')], max_length=10)),
                ('action', models.CharField(choices=[('alert', 'alert'), ('drop', 'drop'), ('reject', 'reject')], max_length=10)),
                ('message', models.CharField(max_length=1000)),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('content', models.CharField(max_length=1000)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('content_location', models.CharField(choices=[('http_uri', 'http_uri'), ('http_client_body', 'http_client_body'), ('http_header', 'http_header')], max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rusicata_manager.service')),
            ],
        ),
    ]
