# Generated by Django 5.2.13 on 2026-05-04 21:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusicata_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='httprule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se la regola è attiva in Suricata'),
        ),
        migrations.AlterField(
            model_name='httprule',
            name='action',
            field=models.CharField(choices=[('alert', 'alert'), ('drop', 'drop'), ('reject', 'reject')], help_text='Azione da eseguire.', max_length=10),
        ),
        migrations.AlterField(
            model_name='httprule',
            name='content',
            field=models.CharField(help_text="Contenuto da bloccare ('TRIGGER')", max_length=1000),
        ),
        migrations.AlterField(
            model_name='httprule',
            name='content_location',
            field=models.CharField(choices=[('http_uri', 'http_uri'), ('http_client_body', 'http_client_body'), ('http_header', 'http_header')], help_text='Dove si trova il content', max_length=20),
        ),
        migrations.AlterField(
            model_name='httprule',
            name='message',
            field=models.CharField(help_text='Messaggio (qualsiasi).', max_length=1000),
        ),
        migrations.AlterField(
            model_name='httprule',
            name='protocol',
            field=models.CharField(choices=[('http', 'http')], help_text='Protocollo sul quale agire.', max_length=10),
        ),
        migrations.AlterField(
            model_name='httprule',
            name='request_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], help_text='Metodo sul quale agire.', max_length=10),
        ),
        migrations.AlterField(
            model_name='httprule',
            name='service',
            field=models.ForeignKey(help_text='Servizio sul quale applicare la regola.', on_delete=django.db.models.deletion.CASCADE, to='rusicata_manager.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Nome del Service', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(help_text='Porta su cui runna (non interna di docker)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.CreateModel(
            name='TransportLevelRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('protocol', models.CharField(choices=[('tcp', 'tcp'), ('udp', 'udp')], help_text='Transport protocol to evaluate.', max_length=10)),
                ('action', models.CharField(choices=[('alert', 'alert'), ('drop', 'drop'), ('reject', 'reject')], help_text='Action to execute.', max_length=10)),
                ('message', models.CharField(help_text='Rule alert message.', max_length=1000)),
                ('content', models.CharField(help_text='Trigger payload content.', max_length=1000)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('flow_direction', models.CharField(choices=[('to_server', 'to_server'), ('to_client', 'to_client'), ('any', 'any')], default='any', help_text='Flow direction.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indica se la regola è attiva in Suricata')),
                ('service', models.ForeignKey(help_text='Service to apply rule.', on_delete=django.db.models.deletion.CASCADE, to='rusicata_manager.service')),
            ],
        ),
    ]
